version: "3"

services:

  nginx:
    build:
      context: ./nginx
    ports:
#       Change to 80:80 if not reverse-proxying with haproxy
      - "8080:80"
    volumes:
#      - ./html:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./conf.d:/etc/nginx/conf.d:ro
      - ./repos:/repos:ro
    restart: always