version: "3"

services:

  nginx:
    build:
      context: ./nginx
    ports:
      - "80:80"
    volumes:
#      - ./html:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./conf.d:/etc/nginx/conf.d:ro
      - ./repos:/repos:ro
#      - /etc/letsencrypt/live/domain.com/fullchain.pem:/etc/nginx/fullchain.pem:ro
#      - /etc/letsencrypt/live/domain.com/privkey.pem:/etc/nginx/privkey.pem:ro
    restart: always